version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db-wallet-challenge
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./Src/Infrastructure/Configuration/Keycloak:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: db-wallet-challenge
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin123
      KC_DB_SCHEMA: keycloak
      KC_FEATURES: token-exchange
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm --verbose

  api:
    build:
      context: ..
      dockerfile: WalletApi/Dockerfile
    container_name: api-wallet
    ports:
      - "8081:80"
    depends_on:
      - postgres
      - keycloak
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=db-wallet-challenge;Username=admin;Password=admin123
      Keycloak__Host: http://keycloak:8080/
      Keycloak__ClientId: wallet-client
      Keycloak__ClientSecret: 9df0GAfuDNwv0hl6r7KuNhTPdiDQfvBX
      Keycloak__GrantType: password
      Keycloak__Realm: wallet_service
      Keycloak__AdminsGroup: ADMINS

volumes:
  pgdata:
